### ISSUE TITLE
Contract Recovery Procedure

### ISSUE THREAD

**Issue by bonedaddy** [verified-network/via-issuer#45]
From https://github.com/verified-network/via-issuer/issues/39

> Need a standard operating procedure to migrate data with current data structures and restore data in new contracts.

**Comment by kallolborah** [comment]
@bonedaddy while we discuss upgrades, its probably better if you can create the recovery and restore process for the following data structures :
1. cash : deposits
2. bonds : bond, bondsIssued, issuers, purchases, issues
3. factory : token, tokens, products, issuers
4. erc20 : balances, totalsupply_ (for each of bond and cash)

**Comment by bonedaddy** [comment]
# ERC20

For this one option is to use the [ERC20Snapshot.sol contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20Snapshot.sol) which would allow us to have on-chain snapshots of token transfers for easy restoration.

**Comment by kallolborah** [comment]
@bonedaddy i like the concept of ERC20snapshot but it is probably an overkill for us. In our case, a simple utility contract will do that can 
1. store a snapshot when any of the following happens
- factory : createToken, createIssuer
- cash : issue, redemption, transfer of cash tokens
- bond : issue, redemption, transfer of bond tokens
2. store the following data structures in the snapshot
- cash : deposits
- bonds : bond, bondsIssued, issuers, purchases, issues
- factory : token, tokens, products, issuers
- erc20 : balances, totalsupply_ (for each of bond, token, and cash)
3. remove the last snapshot taken - since we only need to know last known state for any recovery later on
4. we need a withdraw() function for withdrawl of ether deposited in the cash, bond or token contract. Withdrawals can only be made by the owner/admin of the contracts
5. we need a deposit() function for transfer of ether back from the owner/admin to the respective contracts

**Comment by bonedaddy** [comment]
That makes sense, as long as you can come up with the formula needed for step 3, I can handle the contract programming. Math formulas are not my strong suit.

**Comment by kallolborah** [comment]
@bonedaddy i like the back end ‘service’ but are you saying that this service is a contract too ? Or is it offchain ? Interestingly, I have implemented a Kafka broker based service that listens to some issuance/redemption events because that is fed back to the oracle. Can we perhaps extend that service ? It’s implemented in java. An offchain service also doesn’t incur any gas costs. Although one thing I am wondering here is - how do we emit some complex structures such as cash deposits and the bond structure in bond.sol ?

Alternatively, if we implement a snapshot contract, what costs do we incur ? I am not too worried about maintainability or upgradability of the snapshot contract because I expect it will not change. It will just store what’s passed on to it and make what is stored viewable.

**Comment by kallolborah** [comment]
@bonedaddy the formula (or rather the algorithm) for step 3 could be a simple distance metric.

Thinking loudly here :
 1. In the snapshot contract / back end service, we create two arrays of size =10. Let’s call the first array the ‘bucket’ array (b) and the second one ‘snapshot’ (s) array. The snapshot array stores the last 10 snapshots of any data structure we push to the snapshot contract. The bucket array stores a O(log n) distribution of snapshots over time.

2. Lets now fill in array s with the first 10 snapshots (id=1...10). Once s is filled, we copy s to b. Array s is made empty for the next 10 snapshots coming in.

3. Now, when we copy s snapshots to b, we should first divide the max (snapshot) id by 10 which is always a whole number, m= 1...n. All we need to do then is divide the id of each snapshot in s[1..10] by m, which gives us the place of the snapshot id, p[id]. If b[1...10]>p[id], then we replace b[n] with p[id]. This means only a few bucket elements will change during each interaction of m getting incremented. And not only that, we get a distribution of 10 snapshots over time that are adjusted after every iteration of m.

**Comment by kallolborah** [comment]
@bonedaddy i could also do the algorithm implementation above. You can perhaps just do the rest and push the snapshots into the snapshots array. I will take it from there.

**Comment by bonedaddy** [comment]
> @bonedaddy i could also do the algorithm implementation above. You can perhaps just do the rest and push the snapshots into the snapshots array. I will take it from there.

Sure that works

> Also, for withdrawing and restoring ether and restoring the data in new contracts, better to do a multi-sig operation. What do you think ?

**Comment by kallolborah** [comment]
> @bonedaddy while we discuss upgrades, its probably better if you can create the recovery and restore process for the following data structures :
> 
> 1. cash : deposits
> 2. bonds : bond, bondsIssued, issuers, purchases, issues
> 3. factory : token, tokens, products, issuers
> 4. erc20 : balances, totalsupply_ (for each of bond, token, and cash)

Added events in cash and bond contracts to capture all info required for restoring data.
